forge 'forge.puppetlabs.com'

# Forge Modules
mod 'puppetlabs/ntp', '4.1.2'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/concat'
mod 'puppetlabs/apt'
mod 'puppetlabs/firewall'
mod 'puppetlabs/apache'
mod 'puppetlabs/inifile'
mod 'puppetlabs/vcsrepo'
mod 'mthibaut/users'
mod 'saz/locales'
mod 'theforeman/foreman'
mod 'icinga/icingaweb2'
mod 'dwerder/graphite'
mod 'pdxcat/nrpe'
