forge 'forge.puppetlabs.com'

# Forge Modules
mod 'puppetlabs/java'
mod 'puppetlabs/ruby'
mod 'puppetlabs/ntp'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/concat'
mod 'puppetlabs/apt'
mod 'puppetlabs/firewall'
mod 'puppetlabs/apache'
mod 'puppetlabs/inifile'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/rabbitmq'
mod 'puppetlabs/gcc'
mod 'puppetlabs/git'
mod 'puppetlabs/postgresql'
mod 'mthibaut/users'
mod 'saz/locales'
mod 'theforeman/foreman'
mod 'theforeman/puppet'
mod 'icinga',
  :git => 'https://github.com/Icinga/puppet-icinga2',
  :branch => 'master'
mod 'icinga/icingaweb2'
mod 'dwerder/graphite'
mod 'pdxcat/nrpe'
mod 'maestrodev/wget'
mod 'sensu/sensu'
mod 'arioch-redis'
mod 'nanliu-staging'
mod 'garethr-erlang'
mod 'yelp-uchiwa'
mod 'rtyler/jenkins'
mod 'theforeman/tftp'
mod 'adrien/alternatives'
mod 'puppet/extlib'
